### ISSUE TITLE
Zusätzliche Rolle auf Stufe Region/Kanton

### ISSUE THREAD

**Issue by KunoKunz** [hitobito/hitobito_generic#2]
Auf Stufe Region/Kanton noch eine Admin-Rolle Administrator: [:layer_and_below_full] einfügen.

**Comment by RolandStuder** [comment]
Gibt es bereits, seit dieser Ergänzung: https://github.com/hitobito/hitobito_generic/commit/07047a81af7af961229fdac7129a4f31fc79e867#diff-df5fca08f72628a1fe352307002635e5R20

seit Juni 2018, weiss nicht ob einfach bei neuen Updates der Wagon nicht aktualisiert wurde.
